# Generated by Django 5.0.3 on 2024-05-29 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_jobpostings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpostings',
            old_name='jobDescription',
            new_name='job_description',
        ),
    ]
