# Generated by Django 5.0.3 on 2024-05-30 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_customuser_role_alter_jobpostings_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerdetails',
            name='terms_and_conditions',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='managerdetails',
            name='username',
            field=models.OneToOneField(limit_choices_to={'role': 'manager'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
