# Generated by Django 5.0.3 on 2024-06-04 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_customuser_email_token'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ManagerDetails',
            new_name='TermsAndConditions',
        ),
    ]
