# Generated by Django 5.0.3 on 2024-06-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_managerdetails_termsandconditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostings',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobpostings',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
