# Generated by Django 5.0.3 on 2024-06-04 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_staff_alter_jobpostings_is_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostings',
            name='is_assigned',
            field=models.ForeignKey(limit_choices_to={'role': 'staff'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_jobs', to='app.staff'),
        ),
    ]
