# Generated by Django 5.0.3 on 2024-06-05 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_candidateresume_candidate_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateresume',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
