# Generated by Django 5.0.3 on 2024-06-05 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_resume_id'),
        ('app', '0017_alter_candidateresume_candidate_phone_and_more'),
    ]

    operations = [
    ]
