# Generated by Django 5.0.3 on 2024-06-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_merge_20240605_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostings',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
