# Generated by Django 5.0.3 on 2024-06-06 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_jobpostings_any_bond_jobpostings_decision_maker_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpostings',
            old_name='any_bond',
            new_name='bond',
        ),
    ]
