# Generated by Django 5.0.3 on 2024-06-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_rename_any_bond_jobpostings_bond'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostings',
            name='bond',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobpostings',
            name='decision_maker',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobpostings',
            name='rotational_shift',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='jobpostings',
            name='years_of_experience',
            field=models.IntegerField(),
        ),
    ]
