# Generated by Django 5.0.3 on 2024-06-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_candidateresume_is_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateresume',
            name='status',
            field=models.CharField(choices=[('hired', 'hired'), ('rejected', 'rejected'), ('hold', 'hold')], max_length=20, null=True),
        ),
    ]
