# Generated by Django 5.0.3 on 2024-06-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_candidateresume_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateresume',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('rejected', 'rejected'), ('hold', 'hold'), ('pending', 'pending')], max_length=20, null=True),
        ),
    ]
