# Generated by Django 5.0.3 on 2024-06-13 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_candidateresume_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostings',
            name='interviewer_emails',
            field=models.TextField(default=''),
        ),
    ]
