# Generated by Django 5.0.3 on 2024-06-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_jobpostingedited_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateresume',
            name='message',
            field=models.TextField(default='', null=True),
        ),
    ]
