# Generated by Django 5.0.3 on 2024-06-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_candidateresume_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostingedited',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='candidateresume',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
