# Generated by Django 5.0.3 on 2024-06-17 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_jobpostingedited_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateresume',
            name='job_dept',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='InterviewsSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_description', models.TextField()),
                ('interview_time', models.DateTimeField(default='')),
                ('round_num', models.IntegerField()),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jobpostings')),
                ('resume_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.candidateresume')),
            ],
        ),
    ]
