# Generated by Django 5.0.3 on 2024-06-17 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_candidateresume_job_dept_interviewsschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsschedule',
            name='recruiter_id',
            field=models.ForeignKey(default='', limit_choices_to={'role': 'recruiter'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
