# Generated by Django 5.0.3 on 2024-06-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_interviewerdetails_rounddetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rounddetails',
            old_name='candidate',
            new_name='candidate_name',
        ),
        migrations.RemoveField(
            model_name='jobpostingedited',
            name='interviewer_emails',
        ),
        migrations.RemoveField(
            model_name='jobpostingedited',
            name='interviewers',
        ),
        migrations.AlterField(
            model_name='candidateresume',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('rejected', 'rejected'), ('hold', 'hold'), ('pending', 'pending'), ('round1', 'round1'), ('round2', 'round2'), ('round3', 'round3'), ('round4', 'round4'), ('round5', 'round5'), ('shortlisted', 'shortlisted')], max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='candidateresume',
            constraint=models.UniqueConstraint(fields=('job_id', 'candidate_email'), name='unique_job_id_candidate_email_constraint'),
        ),
    ]
