# Generated by Django 5.0.3 on 2024-06-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_rename_candidate_rounddetails_candidate_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostings',
            name='job_title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
