# Generated by Django 5.0.3 on 2024-06-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_remove_jobpostingedited_interview_process_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rounddetails',
            name='feedback',
            field=models.TextField(default=''),
        ),
    ]
