# Generated by Django 5.0.3 on 2024-06-19 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_rename_candidate_name_rounddetails_candidate_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rounddetails',
            old_name='candidate_id',
            new_name='candidate',
        ),
    ]
