# Generated by Django 5.0.3 on 2024-06-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_rename_candidate_id_rounddetails_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostings',
            name='status',
            field=models.CharField(default='opened', max_length=10),
        ),
    ]
