# Generated by Django 5.0.3 on 2024-06-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_jobpostings_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='Resumes/')),
                ('freeze', models.BooleanField(default=False)),
                ('candidate_name', models.CharField(default='', max_length=40, null=True)),
                ('candidate_email', models.EmailField(default='', max_length=254, null=True)),
                ('contact_number', models.CharField(default='', max_length=15, null=True)),
                ('alternate_contact_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
