# Generated by Django 5.0.6 on 2024-06-28 11:13

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('resume', models.FileField(upload_to='store/resumes/')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='Resumes/')),
                ('freeze', models.BooleanField(default=False)),
                ('freeze_until', models.DateTimeField(blank=True, null=True)),
                ('position', models.CharField(default='', max_length=50, null=True)),
                ('first_name', models.CharField(default='', max_length=30, null=True)),
                ('last_name', models.CharField(default='', max_length=30, null=True)),
                ('middle_name', models.CharField(default='', max_length=30, null=True)),
                ('age', models.PositiveIntegerField(default=1)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('transgender', 'transgender')], max_length=15)),
                ('address', models.TextField(default='', null=True)),
                ('cover_letter', models.TextField(default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('admin', 'admin'), ('candidate', 'candidate'), ('recruiter', 'recruiter'), ('client', 'client'), ('manager', 'manager')], default='user', max_length=50)),
                ('email_token', models.CharField(default='', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CandidateResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='Resumes/')),
                ('candidate_name', models.CharField(default='', max_length=40, null=True)),
                ('candidate_email', models.EmailField(default='', max_length=254, null=True)),
                ('contact_number', models.CharField(default='', max_length=15, null=True)),
                ('alternate_contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('other_details', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('current_organisation', models.CharField(default='', max_length=100, null=True)),
                ('current_job_location', models.CharField(default='', max_length=100, null=True)),
                ('current_job_type', models.CharField(choices=[('permanent', 'Permanent'), ('contract', 'Contract')], default='permanent', max_length=50)),
                ('date_of_birth', models.DateField(null=True)),
                ('total_years_of_experience', models.IntegerField(blank=True, null=True)),
                ('skillset', models.JSONField(blank=True, null=True)),
                ('job_status', models.CharField(choices=[('working', 'working'), ('not_working', 'not_working'), ('serving_notice', 'serving_notice')], max_length=20, null=True)),
                ('current_ctc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expected_ctc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notice_period', models.CharField(blank=True, max_length=50, null=True)),
                ('joining_days_required', models.IntegerField(blank=True, null=True)),
                ('highest_qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('on_hold', models.BooleanField(default=False)),
                ('is_viewed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('accepted', 'accepted'), ('rejected', 'rejected'), ('hold', 'hold'), ('pending', 'pending'), ('round1', 'round1'), ('round2', 'round2'), ('round3', 'round3'), ('round4', 'round4'), ('round5', 'round5'), ('shortlisted', 'shortlisted')], max_length=20, null=True)),
                ('receiver', models.ForeignKey(limit_choices_to={'role': 'client'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_resumes', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(limit_choices_to={'role': 'recruiter'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_resumes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('name_of_organization', models.CharField(max_length=200)),
                ('designation', models.TextField()),
                ('contact_number', models.IntegerField()),
                ('website_url', models.URLField()),
                ('gst', models.CharField(max_length=100)),
                ('company_pan', models.CharField(max_length=20)),
                ('company_address', models.TextField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobPostings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(default='', max_length=255)),
                ('job_department', models.CharField(default='', max_length=100)),
                ('job_description', models.TextField()),
                ('primary_skills', models.TextField()),
                ('secondary_skills', models.TextField(blank=True, null=True)),
                ('years_of_experience', models.IntegerField()),
                ('ctc', models.CharField(max_length=50)),
                ('rounds_of_interview', models.IntegerField()),
                ('job_location', models.CharField(max_length=100)),
                ('job_type', models.CharField(default='', max_length=100)),
                ('job_level', models.CharField(default='', max_length=100)),
                ('qualifications', models.TextField(default='')),
                ('timings', models.CharField(default='', max_length=100)),
                ('other_benefits', models.TextField(default='')),
                ('working_days_per_week', models.IntegerField(default=5)),
                ('decision_maker', models.CharField(default='', max_length=100)),
                ('bond', models.TextField(default='', max_length=255)),
                ('rotational_shift', models.BooleanField()),
                ('status', models.CharField(default='opened', max_length=10)),
                ('is_approved', models.BooleanField(default=True)),
                ('is_assigned', models.ForeignKey(default='', limit_choices_to={'role': 'staff'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_jobs', to=settings.AUTH_USER_MODEL)),
                ('username', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewsSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_description', models.TextField()),
                ('interview_time', models.DateTimeField(default='')),
                ('round_num', models.IntegerField()),
                ('recruiter_id', models.ForeignKey(default='', limit_choices_to={'role': 'recruiter'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('resume_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.candidateresume')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jobpostings')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewerDetailsEdited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_num', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('type_of_interview', models.CharField(choices=[('face_to_face', 'face_to_face'), ('online', 'online'), ('telephone', 'telephone')], max_length=20)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('edited_by', models.CharField(default='', max_length=20)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jobpostings')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_num', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('type_of_interview', models.CharField(choices=[('face_to_face', 'face_to_face'), ('online', 'online'), ('telephone', 'telephone')], max_length=20)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jobpostings')),
            ],
        ),
        migrations.AddField(
            model_name='candidateresume',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='app.jobpostings'),
        ),
        migrations.CreateModel(
            name='RoundDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_num', models.IntegerField(default=0)),
                ('feedback', models.TextField(default='')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.candidateresume')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jobpostings')),
            ],
        ),
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_and_conditions', models.TextField(default='')),
                ('username', models.OneToOneField(limit_choices_to={'role': 'manager'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TermsAndConditionsEdited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_and_conditions', models.TextField(default='')),
                ('username', models.OneToOneField(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobPostingEdited',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.jobpostings')),
                ('job_title', models.CharField(default='', max_length=255)),
                ('job_department', models.CharField(default='', max_length=100)),
                ('job_description', models.TextField()),
                ('primary_skills', models.TextField()),
                ('secondary_skills', models.TextField(blank=True, null=True)),
                ('years_of_experience', models.IntegerField()),
                ('ctc', models.CharField(max_length=50)),
                ('rounds_of_interview', models.IntegerField()),
                ('job_location', models.CharField(max_length=100)),
                ('job_type', models.CharField(default='', max_length=100)),
                ('job_level', models.CharField(default='', max_length=100)),
                ('qualifications', models.TextField(default='')),
                ('timings', models.CharField(default='', max_length=100)),
                ('other_benefits', models.TextField(default='')),
                ('working_days_per_week', models.IntegerField(default=5)),
                ('decision_maker', models.CharField(default='', max_length=100)),
                ('bond', models.TextField(default='', max_length=255)),
                ('rotational_shift', models.BooleanField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('rejected', 'rejected'), ('approved', 'approved')], default='pending', max_length=10)),
                ('message', models.TextField(default='')),
                ('username', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='candidateresume',
            constraint=models.UniqueConstraint(fields=('job_id', 'candidate_email'), name='unique_job_id_candidate_email_constraint'),
        ),
    ]
