# Generated by Django 5.0.6 on 2024-11-04 15:01

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_num', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('type_of_interview', models.CharField(choices=[('face_to_face', 'face_to_face'), ('online', 'online'), ('telephone', 'telephone')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('admin', 'admin'), ('candidate', 'candidate'), ('recruiter', 'recruiter'), ('client', 'client'), ('manager', 'manager')], default='user', max_length=50)),
                ('email_token', models.CharField(default='', max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('credit', models.IntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CandidateResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='Resumes/')),
                ('candidate_name', models.CharField(default='', max_length=40, null=True)),
                ('candidate_email', models.EmailField(default='', max_length=254, null=True)),
                ('contact_number', models.CharField(default='', max_length=15, null=True)),
                ('alternate_contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('other_details', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('current_organisation', models.CharField(blank=True, max_length=100, null=True)),
                ('current_job_location', models.CharField(blank=True, max_length=100, null=True)),
                ('current_job_type', models.CharField(blank=True, choices=[('permanent', 'Permanent'), ('contract', 'Contract')], default='permanent', max_length=50, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('experience', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('current_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('notice_period', models.IntegerField(default=0)),
                ('job_status', models.CharField(choices=[('working', 'working'), ('not_working', 'not_working'), ('serving_notice', 'serving_notice')], default='working', max_length=30)),
                ('receiver', models.ForeignKey(limit_choices_to={'role': 'client'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_resumes', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(limit_choices_to={'role': 'recruiter'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_resumes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('name_of_organization', models.CharField(max_length=200)),
                ('designation', models.TextField()),
                ('contact_number', models.BigIntegerField()),
                ('website_url', models.CharField(max_length=255)),
                ('gst_number', models.CharField(max_length=100)),
                ('company_pan', models.CharField(max_length=20)),
                ('company_address', models.TextField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientTermsAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_date', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.clientdetails')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateTimeField()),
                ('mode_of_interview', models.CharField(choices=[('face_to_face', 'face_to_face'), ('online', 'online'), ('telephone', 'telephone')], max_length=20)),
                ('status', models.CharField(default='Scheduled', max_length=20)),
                ('candidate_resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.candidateresume')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.interviewerdetails')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('interview_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.interviewschedule')),
            ],
        ),
        migrations.CreateModel(
            name='JobPostings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(default='', max_length=255)),
                ('job_department', models.CharField(default='', max_length=100)),
                ('job_description', models.TextField()),
                ('primary_skills', models.TextField()),
                ('secondary_skills', models.TextField(blank=True, null=True)),
                ('years_of_experience', models.IntegerField()),
                ('ctc', models.CharField(max_length=50)),
                ('rounds_of_interview', models.IntegerField()),
                ('job_location', models.CharField(max_length=100)),
                ('job_type', models.CharField(default='', max_length=100)),
                ('job_level', models.CharField(default='', max_length=100)),
                ('qualifications', models.TextField(default='')),
                ('timings', models.CharField(default='', max_length=100)),
                ('other_benefits', models.TextField(default='')),
                ('working_days_per_week', models.IntegerField(default=5)),
                ('decision_maker', models.CharField(default='', max_length=100)),
                ('decision_maker_email', models.CharField(default='', max_length=100)),
                ('bond', models.TextField(default='', max_length=255)),
                ('rotational_shift', models.BooleanField()),
                ('status', models.CharField(default='opened', max_length=10)),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_assigned', models.ForeignKey(blank=True, limit_choices_to={'role': 'recruiter'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_jobs', to=settings.AUTH_USER_MODEL)),
                ('username', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Applied', max_length=50)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.candidateresume')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jobpostings')),
            ],
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jobpostings'),
        ),
        migrations.AddField(
            model_name='interviewerdetails',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jobpostings'),
        ),
        migrations.AddField(
            model_name='candidateresume',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='app.jobpostings'),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='managing_organization', to=settings.AUTH_USER_MODEL)),
                ('recruiters', models.ManyToManyField(blank=True, related_name='recruiting_organization', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.organization'),
        ),
        migrations.CreateModel(
            name='OrganizationTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_fee', models.DecimalField(decimal_places=2, default=8.33, max_digits=5)),
                ('replacement_clause', models.IntegerField(default=90)),
                ('invoice_after', models.IntegerField(default=30)),
                ('payment_within', models.IntegerField(default=7)),
                ('interest_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='app.organization')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=30, null=True)),
                ('last_name', models.CharField(default='', max_length=30, null=True)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=15)),
                ('address', models.TextField(default='', null=True)),
                ('phone_number', models.CharField(default='', max_length=15, null=True)),
                ('accepted_terms', models.BooleanField(default=False)),
                ('accepted_date', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
