# Generated by Django 5.0.6 on 2025-04-21 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='editor',
        ),
    ]
