# Generated by Django 5.0.6 on 2024-11-04 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientdetails',
            old_name='email',
            new_name='user',
        ),
    ]
