# Generated by Django 5.0.6 on 2025-04-14 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostings',
            name='jobcode',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='jobpostings',
            unique_together={('username', 'jobcode')},
        ),
    ]
