# Generated by Django 5.0.6 on 2025-01-13 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpostingseditedversion',
            name='is_accepted',
        ),
        migrations.AddField(
            model_name='jobpostingseditedversion',
            name='status',
            field=models.TextField(choices=[('accepted', 'accepted'), ('rejected', 'rejected'), ('pending', 'pending')], default='pending'),
        ),
    ]
