# Generated by Django 5.0.6 on 2024-06-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email_token',
            field=models.CharField(default='', max_length=50),
        ),
    ]
