# Generated by Django 5.0.6 on 2024-07-23 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostings',
            name='decision_maker_email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobpostings',
            name='is_assigned',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'recruiter'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
