# Generated by Django 5.0.3 on 2024-05-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostings',
            name='years_of_experience',
            field=models.IntegerField(default=0),
        ),
    ]
