# Generated by Django 5.0.6 on 2024-07-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_jobpostings_decision_maker_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateresume',
            name='current_job_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidateresume',
            name='current_job_type',
            field=models.CharField(blank=True, choices=[('permanent', 'Permanent'), ('contract', 'Contract')], default='permanent', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidateresume',
            name='current_organisation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidateresume',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateresume',
            name='job_status',
            field=models.CharField(blank=True, choices=[('working', 'working'), ('not_working', 'not_working'), ('serving_notice', 'serving_notice')], max_length=20, null=True),
        ),
    ]
