# Generated by Django 5.0.6 on 2025-04-24 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='category',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
