# Generated by Django 5.0.6 on 2024-11-05 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_email_clientdetails_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_token',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_verified',
        ),
    ]
