# Generated by Django 5.0.6 on 2025-04-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_jobpostings_jobcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostingseditedversion',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('rejected', 'rejected'), ('pending', 'pending')], default='pending', max_length=20),
        ),
    ]
