# Generated by Django 5.0.6 on 2024-06-29 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customuser_email_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpostingedited',
            old_name='status',
            new_name='edit_status',
        ),
    ]
