# Generated by Django 5.0.6 on 2025-01-15 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_primaryskillset_secondaryskillset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateresume',
            name='primary_skills',
        ),
        migrations.RemoveField(
            model_name='candidateresume',
            name='secondary_skills',
        ),
    ]
