# Generated by Django 5.0.6 on 2025-04-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposteditfields',
            name='field_value',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
