# Generated by Django 5.0.6 on 2025-01-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_jobpostingseditedversion_is_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostings',
            name='notice_time',
            field=models.CharField(default=' ', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jobpostings',
            name='time_period',
            field=models.CharField(default=' ', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobpostingseditedversion',
            name='notice_period',
            field=models.CharField(default=' ', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jobpostingseditedversion',
            name='time_period',
            field=models.CharField(default=' ', max_length=50, null=True),
        ),
    ]
