# Generated by Django 5.0.6 on 2025-04-17 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_jobpostingseditedversion_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostings',
            name='jobcode',
            field=models.CharField(default='jcd0', max_length=10),
        ),
        migrations.AlterField(
            model_name='jobpostingseditedversion',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobpostingseditedversion',
            name='version_number',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
