# Generated by Django 5.0.6 on 2024-11-06 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_customuser_email_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostings',
            name='orgaization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='org_code',
            field=models.CharField(default='GA001', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
