# Generated by Django 5.0.6 on 2024-10-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_candidateresume_current_job_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostings',
            name='custom_job_level',
            field=models.CharField(default='', max_length=50),
        ),
    ]
