# Generated by Django 5.0.6 on 2024-07-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_status_jobpostingedited_edit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetails',
            name='contact_number',
            field=models.BigIntegerField(),
        ),
    ]
