# Generated by Django 5.0.6 on 2025-01-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_jobpostings_notice_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostings',
            name='notice_time',
            field=models.CharField(blank=True, default=' ', max_length=30),
        ),
        migrations.AlterField(
            model_name='jobpostings',
            name='time_period',
            field=models.CharField(blank=True, default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobpostingseditedversion',
            name='notice_period',
            field=models.CharField(blank=True, default=' ', max_length=30),
        ),
        migrations.AlterField(
            model_name='jobpostingseditedversion',
            name='time_period',
            field=models.CharField(blank=True, default=' ', max_length=50),
        ),
    ]
