# Generated by Django 5.0.6 on 2025-01-15 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_candidateresume_primary_skills_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='candidateresume',
            unique_together={('job_id', 'candidate_email')},
        ),
    ]
