# Generated by Django 5.0.6 on 2025-05-05 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_jobposteditfields_field_value_and_more'),
        ('app', '0004_alter_notifications_category'),
    ]

    operations = [
    ]
