# Generated by Django 5.0.6 on 2025-01-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_candidateresume_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='feedback',
            field=models.TextField(default='empty'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('selected', 'selected'), ('rejected', 'rejected'), ('hold', 'hold'), ('pending', 'pending'), ('applied', 'applied')], default='applied', max_length=50),
        ),
    ]
