# Generated by Django 5.0.6 on 2025-01-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_jobpostings_notice_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidateresume',
            old_name='current_salary',
            new_name='current_ctc',
        ),
        migrations.AddField(
            model_name='candidateresume',
            name='expected_ctc',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
