# Generated by Django 5.0.6 on 2025-05-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_merge_20250501_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
