# Generated by Django 5.0.6 on 2024-10-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_jobpostings_custom_job_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostings',
            name='custom_ctc_range',
            field=models.CharField(default='', max_length=50),
        ),
    ]
