# Generated by Django 5.0.6 on 2024-11-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_jobpostings_orgaization_organization_org_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='company_address',
            field=models.CharField(default='a', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='company_pan',
            field=models.CharField(default='a', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='contact_number',
            field=models.CharField(default='a', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='gst_number',
            field=models.CharField(default='a', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='website_url',
            field=models.CharField(default='a', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
