# Generated by Django 5.0.6 on 2024-07-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_clientdetails_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
