# Generated by Django 5.0.6 on 2025-01-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_jobapplication_feedback_alter_jobapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='feedback',
            field=models.TextField(blank=True, default=None),
        ),
    ]
