# Generated by Django 5.0.6 on 2025-04-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
