# Generated by Django 5.0.6 on 2025-05-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_merge_20250505_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negotiationrequests',
            name='is_accepted',
        ),
        migrations.AddField(
            model_name='negotiationrequests',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('pending', 'pending'), ('rejected', 'rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='category',
            field=models.CharField(blank=True, choices=[('negotiated_terms', 'NegotiatedTerms'), ('reject_terms', 'RejectTerms'), ('accept_terms', 'AcceptTerms'), ('create_job', 'CreateJob'), ('assign_interviewer', 'AssignInterviewer'), ('accept_job', 'AcceptJob'), ('edit_job', 'EditJob'), ('accept_job_edit', 'AcceptJobEdit'), ('reject_job_edit', 'RejectJobEdit'), ('partial_job_edit', 'PartialJobEdit'), ('reject_job', 'RejectJob'), ('assign_job', 'AssignJob'), ('send_application', 'SendApplication'), ('shortlist_application', 'ShortlistApplication'), ('schedule_interview', 'ScheduleInterview'), ('promote_candidate', 'PromoteCandidate'), ('reject_candidate', 'RejectCandidate'), ('onhold_candidate', 'OnHoldCandidate'), ('select_candidate', 'SelectCandidate'), ('accepted_ctc', 'AcceptedCTC'), ('candidate_accepted', 'CandidateAccepted'), ('candidate_rejected', 'CandidateRejected'), ('candidate_left', 'CandidateLeft'), ('candidate_joined', 'CandidateJoined')], max_length=60, null=True),
        ),
    ]
