# Generated by Django 5.0.6 on 2024-10-25 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_jobpostings_custom_ctc_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpostings',
            name='custom_ctc_range',
        ),
        migrations.RemoveField(
            model_name='jobpostings',
            name='custom_job_level',
        ),
    ]
