# Generated by Django 5.0.6 on 2024-11-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_organization_company_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
