# Generated by Django 5.0.6 on 2024-07-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_candidateresume_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateresume',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
