# Generated by Django 5.0.6 on 2025-04-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_notifications_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='editor_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
