# Generated by Django 5.0.6 on 2024-11-06 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_organization_is_subscribed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpostings',
            old_name='orgaization',
            new_name='organization',
        ),
    ]
