# Generated by Django 5.0.6 on 2025-05-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_negotiationrequests_is_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiationrequests',
            name='reason',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='negotiationrequests',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
