# Generated by Django 5.0.6 on 2025-01-15 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_candidateevaluation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='next_interview',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='app.interviewschedule'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='round_num',
            field=models.IntegerField(default=0),
        ),
    ]
