# Generated by Django 5.0.6 on 2024-11-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_orgaization_jobpostings_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateresume',
            name='candidate_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='candidateresume',
            name='candidate_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='candidateresume',
            name='contact_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='candidateresume',
            name='other_details',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobpostings',
            name='bond',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobpostings',
            name='decision_maker',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobpostings',
            name='decision_maker_email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobpostings',
            name='job_department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobpostings',
            name='job_level',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobpostings',
            name='job_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobpostings',
            name='job_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobpostings',
            name='other_benefits',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobpostings',
            name='qualifications',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobpostings',
            name='timings',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
