# Generated by Django 5.0.6 on 2025-04-21 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_notifications_editor_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='editor_name',
            new_name='editor',
        ),
    ]
