# Generated by Django 5.0.6 on 2025-05-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_negotiationrequests_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpostings',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='jobpostings',
            name='reason',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
