# Generated by Django 5.0.6 on 2024-11-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_candidateresume_candidate_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewerdetails',
            name='round_num',
            field=models.IntegerField(),
        ),
    ]
