# Generated by Django 5.0.6 on 2025-01-16 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_jobapplication_next_interview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienttermsacceptance',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
