# Generated by Django 5.0.6 on 2025-05-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_jobpostings_is_approved_jobpostings_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostings',
            name='jobcode',
            field=models.CharField(default='jcd0', max_length=40),
        ),
    ]
