# Generated by Django 5.0.3 on 2024-06-04 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_jobpostings_is_approved_jobpostings_is_assigned'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.ForeignKey(limit_choices_to={'role': 'recruiter'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='jobpostings',
            name='is_assigned',
            field=models.ForeignKey(default='', limit_choices_to={'role': 'staff'}, on_delete=django.db.models.deletion.CASCADE, to='app.staff'),
        ),
    ]
