# Generated by Django 5.0.6 on 2025-04-21 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_editor_name_notifications_editor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notifications',
            new_name='NotificationsModel',
        ),
    ]
