# Generated by Django 5.0.6 on 2025-05-07 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_customuser_first_login_and_more'),
        ('app', '0009_alter_jobpostings_jobcode'),
    ]

    operations = [
    ]
