# Generated by Django 5.0.6 on 2024-11-14 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_interviewerdetails_round_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='accepted_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='accepted_terms',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='valid_until',
        ),
        migrations.AddField(
            model_name='clienttermsacceptance',
            name='interest_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='clienttermsacceptance',
            name='invoice_after',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='clienttermsacceptance',
            name='organization',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='client_terms', to='app.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clienttermsacceptance',
            name='payment_within',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='clienttermsacceptance',
            name='replacement_clause',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='clienttermsacceptance',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=8.33, max_digits=5),
        ),
        migrations.CreateModel(
            name='NegotiationRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_fee', models.DecimalField(decimal_places=2, default=8.33, max_digits=5)),
                ('replacement_clause', models.IntegerField(default=90)),
                ('invoice_after', models.IntegerField(default=30)),
                ('payment_within', models.IntegerField(default=7)),
                ('interest_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('requested_date', models.DateTimeField(auto_now_add=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('accepted_date', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.clientdetails')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='negotiation_client_terms', to='app.organization')),
            ],
        ),
    ]
