# Generated by Django 5.0.6 on 2024-11-14 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_userprofile_accepted_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttermsacceptance',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_terms', to='app.organization'),
        ),
        migrations.AlterField(
            model_name='negotiationrequests',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiation_client_terms', to='app.organization'),
        ),
    ]
