# Generated by Django 5.0.6 on 2025-05-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_merge_20250507_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewschedule',
            name='status',
            field=models.CharField(choices=[('scheduled', 'scheduled'), ('pending', 'pending'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='scheduled', max_length=20),
        ),
    ]
