# Generated by Django 5.0.6 on 2025-01-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_organizationterms_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiationrequests',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
