# Generated by Django 5.0.3 on 2024-06-04 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_jobpostings_is_assigned_delete_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostings',
            name='is_assigned',
            field=models.ForeignKey(default='', limit_choices_to={'role': 'staff'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
