# Generated by Django 5.0.6 on 2025-05-13 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_interviewschedule_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='attached_to',
            field=models.ForeignKey(limit_choices_to={'role': 'recruiter'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_resumes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='sender',
            field=models.ForeignKey(limit_choices_to={'role': 'recruiter'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Actual_sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
