# Generated by Django 5.0.6 on 2025-01-16 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_negotiationrequests_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='feedback',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
