# Generated by Django 5.0.6 on 2025-01-02 05:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_clienttermsacceptance_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='recruiters',
            field=models.ManyToManyField(blank=True, null=True, related_name='recruiting_organization', to=settings.AUTH_USER_MODEL),
        ),
    ]
