# Generated by Django 5.0.3 on 2024-06-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_jobpostings_is_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostings',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
