# Generated by Django 5.0.6 on 2025-05-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_jobapplication_attached_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedcandidates',
            name='edit_request',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
