# Generated by Django 5.0.6 on 2025-01-16 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_jobapplication_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='next_interview',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.interviewschedule'),
        ),
    ]
