# Generated by Django 5.0.6 on 2025-01-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_organization_recruiters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpostings',
            old_name='job_location',
            new_name='job_locations',
        ),
        migrations.AddField(
            model_name='interviewerdetails',
            name='mode_of_interview',
            field=models.CharField(choices=[('face_to_face', 'face_to_face'), ('online', 'online'), ('telephone', 'telephone')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='jobpostings',
            name='age',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='jobpostings',
            name='differently_abled',
            field=models.CharField(default=' ', max_length=40),
        ),
        migrations.AddField(
            model_name='jobpostings',
            name='gender',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='jobpostings',
            name='industry',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='jobpostings',
            name='languages',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='jobpostings',
            name='notice_time',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='jobpostings',
            name='qualification_department',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='jobpostings',
            name='time_period',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='jobpostings',
            name='visa_status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='interviewerdetails',
            name='type_of_interview',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='jobpostings',
            name='years_of_experience',
            field=models.TextField(max_length=100),
        ),
    ]
