# Generated by Django 5.0.6 on 2025-05-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_selectedcandidates_edit_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedcandidates',
            name='client_accept_request',
            field=models.BooleanField(default=False),
        ),
    ]
