# Generated by Django 5.0.3 on 2024-06-05 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_jobpostings_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='./media/Resumes')),
                ('candidate_name', models.CharField(default='', max_length=40, null=True)),
                ('candidate_email', models.EmailField(default='', max_length=254, null=True)),
                ('candidate_phone', models.IntegerField(default='', max_length=10, null=True)),
                ('other_details', models.CharField(default='', max_length=100, null=True)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_id', to='app.jobpostings')),
                ('receiver', models.ForeignKey(default='', limit_choices_to={'role': 'client'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(default='', limit_choices_to={'role': 'recruiter'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
