# Generated by Django 5.0.6 on 2025-01-16 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_jobapplication_next_interview'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='candidateresume',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='receiver',
            field=models.ForeignKey(limit_choices_to={'role': 'client'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_resumes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='sender',
            field=models.ForeignKey(limit_choices_to={'role': 'recruiter'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_resumes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('job_id', 'resume')},
        ),
        migrations.RemoveField(
            model_name='candidateresume',
            name='job_id',
        ),
        migrations.RemoveField(
            model_name='candidateresume',
            name='message',
        ),
        migrations.RemoveField(
            model_name='candidateresume',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='candidateresume',
            name='sender',
        ),
    ]
