# Generated by Django 5.0.6 on 2025-01-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_job_location_jobpostings_job_locations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostings',
            name='notice_period',
            field=models.CharField(default='', max_length=30),
        ),
    ]
