# Generated by Django 5.0.6 on 2025-01-09 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_jobpostings_notice_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPostingsEditedVersion',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.jobpostings')),
                ('job_title', models.CharField(max_length=255)),
                ('job_department', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
                ('primary_skills', models.TextField()),
                ('secondary_skills', models.TextField(blank=True, null=True)),
                ('years_of_experience', models.TextField(max_length=100)),
                ('ctc', models.CharField(max_length=50)),
                ('rounds_of_interview', models.IntegerField()),
                ('job_locations', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=100)),
                ('job_level', models.CharField(max_length=100)),
                ('qualifications', models.TextField()),
                ('timings', models.CharField(max_length=100)),
                ('other_benefits', models.TextField()),
                ('working_days_per_week', models.IntegerField(default=5)),
                ('decision_maker', models.CharField(max_length=100)),
                ('decision_maker_email', models.CharField(max_length=100)),
                ('bond', models.TextField(max_length=255)),
                ('rotational_shift', models.BooleanField()),
                ('age', models.CharField(default='', max_length=255)),
                ('gender', models.CharField(default='', max_length=100)),
                ('visa_status', models.CharField(default='', max_length=100)),
                ('time_period', models.CharField(default='', max_length=50)),
                ('qualification_department', models.CharField(default='', max_length=50)),
                ('notice_period', models.CharField(default='', max_length=30)),
                ('notice_time', models.CharField(default='', max_length=30)),
                ('industry', models.CharField(default='', max_length=40)),
                ('differently_abled', models.CharField(default=' ', max_length=40)),
                ('languages', models.CharField(default=' ', max_length=100)),
                ('is_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('edited_by', models.ForeignKey(limit_choices_to={'role': 'manager'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
