# Generated by Django 5.0.6 on 2025-01-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_candidateresume_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewschedule',
            name='candidate_resume',
        ),
        migrations.AlterField(
            model_name='interviewerdetails',
            name='round_num',
            field=models.IntegerField(default=0),
        ),
    ]
