# Generated by Django 5.0.3 on 2024-06-05 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_candidateresume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateresume',
            name='candidate_phone',
            field=models.IntegerField(default='', null=True),
        ),
    ]
