# Generated by Django 5.0.6 on 2025-06-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_selectedcandidates_client_accept_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewschedule',
            name='status',
            field=models.CharField(choices=[('scheduled', 'scheduled'), ('pending', 'pending'), ('completed', 'completed'), ('cancelled', 'cancelled'), ('reschedule', 'reschedule')], default='scheduled', max_length=20),
        ),
    ]
