# Generated by Django 5.0.6 on 2025-06-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_interviewschedule_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostings',
            name='is_linkedin_posted',
            field=models.BooleanField(default=False),
        ),
    ]
