# Generated by Django 5.0.6 on 2025-01-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_interviewschedule_candidate_resume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateevaluation',
            name='primary_skills_rating',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='candidateevaluation',
            name='round_num',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidateevaluation',
            name='secondary_skills_ratings',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('selected', 'selected'), ('rejected', 'rejected'), ('hold', 'hold'), ('pending', 'pending'), ('applied', 'applied'), ('processing', 'processing')], default='applied', max_length=50),
        ),
    ]
