# Generated by Django 5.0.6 on 2025-01-09 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_jobpostingseditedversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostingseditedversion',
            name='organization',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.organization'),
        ),
    ]
