# Generated by Django 5.0.3 on 2024-06-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_candidateresume_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateresume',
            name='candidate_phone',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='candidateresume',
            name='resume',
            field=models.FileField(upload_to='Resumes/'),
        ),
    ]
