# Generated by Django 5.0.6 on 2025-01-09 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_jobpostingseditedversion_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewerDetailsEditedVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_num', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mode_of_interview', models.CharField(choices=[('face_to_face', 'face_to_face'), ('online', 'online'), ('telephone', 'telephone')], default='', max_length=20)),
                ('type_of_interview', models.CharField(default='', max_length=35)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jobpostingseditedversion')),
            ],
        ),
    ]
