# Generated by Django 5.0.6 on 2025-06-09 09:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_jobpostings_is_linkedin_posted'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedinIntegrations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('linkedin_user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('organization_urn', models.CharField(blank=True, max_length=255, null=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_linkedin_connected', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.organization')),
            ],
            options={
                'verbose_name': 'Agency Linkedin Integration',
                'verbose_name_plural': 'Agency Linkedin Integrations',
            },
        ),
    ]
