# Generated by Django 5.0.6 on 2025-01-20 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_candidateevaluation_primary_skills_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateevaluation',
            name='job_application',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.jobapplication'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidateevaluation',
            name='job_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.jobpostings'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='candidateevaluation',
            unique_together={('job_id', 'job_application')},
        ),
    ]
