# Generated by Django 5.0.6 on 2025-01-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_interviewerdetailseditedversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewerdetails',
            name='mode_of_interview',
            field=models.CharField(blank=True, choices=[('face_to_face', 'face_to_face'), ('online', 'online'), ('telephone', 'telephone')], max_length=20, null=True),
        ),
    ]
