# Generated by Django 5.0.6 on 2025-06-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_linkedinintegrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinintegrations',
            name='contact_person',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linkedinintegrations',
            name='email',
            field=models.EmailField(default='kalki1234@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linkedinintegrations',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
