# Generated by Django 5.0.6 on 2025-01-20 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_candidateevaluation_job_application_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='candidateevaluation',
            unique_together={('job_id', 'job_application', 'round_num')},
        ),
    ]
