# Generated by Django 5.0.6 on 2025-06-10 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_linkedinintegrations_contact_person_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkedinintegrations',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='linkedinintegrations',
            name='email',
        ),
        migrations.RemoveField(
            model_name='linkedinintegrations',
            name='phone_number',
        ),
    ]
