# Generated by Django 5.0.6 on 2025-01-20 11:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_candidateevaluation_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='recruiters',
            field=models.ManyToManyField(blank=True, related_name='recruiting_organization', to=settings.AUTH_USER_MODEL),
        ),
    ]
