# Generated by Django 5.0.6 on 2025-06-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_linkedinintegrations_contact_person_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiresyncLinkedinCred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_urn', models.CharField(blank=True, max_length=255, null=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Hiresync Integration',
            },
        ),
    ]
