# Generated by Django 5.0.3 on 2024-06-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_jobpostings_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostings',
            name='any_bond',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='jobpostings',
            name='decision_maker',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='jobpostings',
            name='interview_process',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='jobpostings',
            name='job_level',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='jobpostings',
            name='job_title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='jobpostings',
            name='job_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='jobpostings',
            name='other_benefits',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='jobpostings',
            name='qualifications',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='jobpostings',
            name='rotational_shift',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='jobpostings',
            name='timings',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='jobpostings',
            name='working_days_per_week',
            field=models.IntegerField(default=5),
        ),
    ]
