# Generated by Django 5.0.6 on 2025-01-21 05:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_organization_recruiters'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='interviewers',
            field=models.ManyToManyField(blank=True, related_name='client_interviewers', to=settings.AUTH_USER_MODEL),
        ),
    ]
