# Generated by Django 5.0.6 on 2025-06-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_hiresynclinkedincred'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['email'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('candidate', 'candidate'), ('recruiter', 'recruiter'), ('client', 'client'), ('manager', 'manager'), ('interviewer', 'interviewer'), ('accountant', 'accountant')], default='admin', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
