# Generated by Django 5.0.6 on 2025-01-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_clientdetails_interviewers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('candidate', 'candidate'), ('recruiter', 'recruiter'), ('client', 'client'), ('manager', 'manager'), ('interviewer', 'interviewer')], default='user', max_length=50),
        ),
    ]
