# Generated by Django 5.0.6 on 2025-01-21 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewerdetailseditedversion',
            name='email',
        ),
        migrations.AlterField(
            model_name='interviewerdetailseditedversion',
            name='name',
            field=models.ForeignKey(limit_choices_to={'role': 'interviewer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
