# Generated by Django 5.0.6 on 2025-06-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_customuser_options_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_incoming',
            field=models.BooleanField(default=False),
        ),
    ]
