# Generated by Django 5.0.3 on 2024-06-07 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_jobpostings_bond_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateresume',
            name='candidate_phone',
        ),
        migrations.AddField(
            model_name='candidateresume',
            name='alternate_contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='candidateresume',
            name='contact_number',
            field=models.CharField(default='', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='candidateresume',
            name='current_ctc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='candidateresume',
            name='current_job_location',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidateresume',
            name='current_job_type',
            field=models.CharField(choices=[('permanent', 'Permanent'), ('contract', 'Contract')], default='permanent', max_length=50),
        ),
        migrations.AddField(
            model_name='candidateresume',
            name='current_organisation',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidateresume',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='candidateresume',
            name='expected_ctc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='candidateresume',
            name='highest_qualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidateresume',
            name='job_status',
            field=models.CharField(choices=[('working', 'working'), ('not_working', 'not_working'), ('serving_notice', 'serving_notice')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='candidateresume',
            name='joining_days_required',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateresume',
            name='notice_period',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidateresume',
            name='skillset',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateresume',
            name='total_years_of_experience',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='candidateresume',
            name='years_of_experience_in_cloud',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='candidateresume',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='app.jobpostings'),
        ),
        migrations.AlterField(
            model_name='candidateresume',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateresume',
            name='other_details',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidateresume',
            name='receiver',
            field=models.ForeignKey(limit_choices_to={'role': 'client'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_resumes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='candidateresume',
            name='sender',
            field=models.ForeignKey(limit_choices_to={'role': 'recruiter'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_resumes', to=settings.AUTH_USER_MODEL),
        ),
    ]
