# Generated by Django 5.0.6 on 2025-06-17 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_jobapplication_is_incoming'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpostings',
            name='job_locations',
        ),
        migrations.RemoveField(
            model_name='jobpostings',
            name='num_of_positions',
        ),
        migrations.CreateModel(
            name='JobLocationsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('job_type', models.CharField(choices=[('remote', 'remote'), ('hybrid', 'hybrid'), ('office', 'office')], max_length=10)),
                ('positions', models.IntegerField(default=0)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jobpostings')),
            ],
        ),
    ]
