# Generated by Django 5.0.6 on 2025-01-22 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_interviewerdetails_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primaryskillset',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_skills', to='app.candidateresume'),
        ),
        migrations.AlterField(
            model_name='secondaryskillset',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_skills', to='app.candidateresume'),
        ),
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('address', models.TextField(null=True)),
                ('phone_num', models.TextField(null=True)),
                ('date_of_birth', models.DateField(blank=True, default=None, null=True)),
                ('socialMediaLinks', models.TextField(null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='candidateresume',
            name='candidate_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to='app.candidateprofile'),
        ),
    ]
