# Generated by Django 5.0.6 on 2025-06-17 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_jobpostings_job_locations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPostingDraftVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobcode', models.CharField(blank=True, default='jcd0', max_length=40)),
                ('current_step', models.IntegerField(default=1)),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('job_department', models.CharField(blank=True, max_length=100)),
                ('job_description', models.TextField(blank=True)),
                ('years_of_experience', models.CharField(blank=True, max_length=100)),
                ('ctc', models.CharField(blank=True, max_length=50)),
                ('rounds_of_interview', models.IntegerField(blank=True, null=True)),
                ('job_type', models.CharField(blank=True, max_length=100)),
                ('probation_type', models.CharField(blank=True, max_length=20)),
                ('job_level', models.CharField(blank=True, max_length=100)),
                ('qualifications', models.TextField(blank=True)),
                ('timings', models.CharField(blank=True, max_length=100)),
                ('other_benefits', models.TextField(blank=True)),
                ('working_days_per_week', models.IntegerField(blank=True, default=5, null=True)),
                ('decision_maker', models.CharField(blank=True, max_length=100)),
                ('decision_maker_email', models.CharField(blank=True, max_length=100)),
                ('bond', models.CharField(blank=True, max_length=255)),
                ('rotational_shift', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, default='opened', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('age', models.CharField(blank=True, max_length=255)),
                ('gender', models.CharField(blank=True, max_length=100)),
                ('visa_status', models.CharField(blank=True, max_length=100)),
                ('passport_availability', models.CharField(blank=True, max_length=50)),
                ('time_period', models.CharField(blank=True, default='', max_length=50)),
                ('qualification_department', models.CharField(blank=True, max_length=50)),
                ('notice_period', models.CharField(blank=True, max_length=30)),
                ('notice_time', models.CharField(blank=True, default='', max_length=30)),
                ('industry', models.CharField(blank=True, max_length=40)),
                ('differently_abled', models.CharField(blank=True, max_length=40)),
                ('languages', models.CharField(blank=True, max_length=100)),
                ('job_close_duration', models.DateField(blank=True, null=True)),
                ('approval_status', models.CharField(blank=True, default='pending', max_length=10)),
                ('reason', models.TextField(blank=True, default='', null=True)),
                ('is_linkedin_posted', models.BooleanField(default=False)),
                ('assigned_to', models.ManyToManyField(blank=True, limit_choices_to={'role': 'recruiter'}, related_name='assigned_jobs_draft', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.organization')),
                ('username', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('username', 'jobcode')},
            },
        ),
        migrations.CreateModel(
            name='JobLocationsDraftVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=50)),
                ('job_type', models.CharField(blank=True, choices=[('remote', 'remote'), ('hybrid', 'hybrid'), ('office', 'office')], max_length=10)),
                ('positions', models.IntegerField(blank=True, default=0, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='app.jobpostingdraftversion')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewerDetailsDraftVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_num', models.IntegerField(blank=True, default=0, null=True)),
                ('mode_of_interview', models.CharField(blank=True, choices=[('face_to_face', 'Face to Face'), ('online', 'Online'), ('telephone', 'Telephone')], max_length=20)),
                ('type_of_interview', models.CharField(blank=True, choices=[('technical', 'Technical'), ('non-technical', 'Non-Technical'), ('assignment', 'Assignment')], max_length=35)),
                ('name', models.ForeignKey(blank=True, limit_choices_to={'role': 'interviewer'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviewers', to='app.jobpostingdraftversion')),
            ],
        ),
        migrations.CreateModel(
            name='SkillMetricsDraftVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(blank=True, max_length=50)),
                ('is_primary', models.BooleanField(default=False)),
                ('metric_type', models.CharField(blank=True, max_length=100)),
                ('metric_value', models.CharField(blank=True, max_length=100)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_metrics', to='app.jobpostingdraftversion')),
            ],
        ),
    ]
