# Generated by Django 5.0.3 on 2024-06-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_candidateresume_candidate_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateresume',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidateresume',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidateresume',
            name='on_hold',
            field=models.BooleanField(default=False),
        ),
    ]
