# Generated by Django 5.0.3 on 2024-06-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_candidateresume_is_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateresume',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
