# Generated by Django 5.0.6 on 2025-06-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_jobpostingdraftversion_joblocationsdraftversion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostingdraftversion',
            name='probation_period',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
