# Generated by Django 5.0.6 on 2025-06-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_jobpostingdraftversion_probation_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpostings',
            name='qualification_department',
        ),
        migrations.AddField(
            model_name='jobpostings',
            name='probation_period',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='jobpostings',
            name='bond',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='jobpostings',
            name='decision_maker',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='jobpostings',
            name='decision_maker_email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='jobpostings',
            name='differently_abled',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='jobpostings',
            name='gender',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='jobpostings',
            name='job_level',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='jobpostings',
            name='languages',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='jobpostings',
            name='other_benefits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobpostings',
            name='working_days_per_week',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
