# Generated by Django 5.0.6 on 2025-01-23 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_candidateprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewschedule',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.candidateresume'),
        ),
    ]
