# Generated by Django 5.0.6 on 2025-06-20 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_jobpostings_qualification_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpostings',
            name='assigned_to',
        ),
        migrations.CreateModel(
            name='AssignedJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_to', models.ManyToManyField(blank=True, limit_choices_to={'role': 'recruiter'}, related_name='assigned_jobs', to=settings.AUTH_USER_MODEL)),
                ('job_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.joblocationsmodel')),
            ],
        ),
    ]
