# Generated by Django 5.0.6 on 2025-06-20 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_jobpostings_assigned_to_assignedjobs'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='assignedjobs',
            name='job_id',
            field=models.ForeignKey(default='7', on_delete=django.db.models.deletion.CASCADE, to='app.jobpostings'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job_location',
            field=models.ForeignKey(default='7', on_delete=django.db.models.deletion.CASCADE, to='app.joblocationsmodel'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='job_id',
        ),
    ]
