# Generated by Django 5.0.6 on 2025-01-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_interviewschedule_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateresume',
            name='candidate_name',
            field=models.CharField(max_length=100),
        ),
    ]
