# Generated by Django 5.0.6 on 2025-06-20 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_jobapplication_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('job_location', 'resume')},
        ),
    ]
