# Generated by Django 5.0.6 on 2025-01-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_candidateresume_candidate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='Candidate/Profile/'),
        ),
    ]
