# Generated by Django 5.0.3 on 2024-06-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_jobpostings_interviewer_emails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateresume',
            name='years_of_experience_in_cloud',
        ),
        migrations.AlterField(
            model_name='candidateresume',
            name='total_years_of_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
