# Generated by Django 5.0.6 on 2025-06-23 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_jobapplication_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='candidateevaluation',
            unique_together={('job_application', 'round_num')},
        ),
        migrations.RemoveField(
            model_name='interviewschedule',
            name='job_id',
        ),
        migrations.AddField(
            model_name='candidateevaluation',
            name='job_location',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='app.joblocationsmodel'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='candidateevaluation',
            name='job_id',
        ),
    ]
