# Generated by Django 5.0.6 on 2025-06-23 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_candidateevaluation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewschedule',
            name='job_location',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='app.joblocationsmodel'),
            preserve_default=False,
        ),
    ]
