# Generated by Django 5.0.3 on 2024-06-13 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_remove_candidateresume_years_of_experience_in_cloud_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPostingEdited',
            fields=[
                ('job_title', models.CharField(default='', max_length=255, primary_key=True, serialize=False, unique=True)),
                ('job_description', models.TextField()),
                ('primary_skills', models.TextField()),
                ('secondary_skills', models.TextField(blank=True, null=True)),
                ('years_of_experience', models.IntegerField()),
                ('ctc', models.CharField(max_length=50)),
                ('rounds_of_interview', models.IntegerField()),
                ('interviewers', models.TextField()),
                ('interviewer_emails', models.TextField(default='')),
                ('job_location', models.CharField(max_length=100)),
                ('job_type', models.CharField(default='', max_length=100)),
                ('job_level', models.CharField(default='', max_length=100)),
                ('qualifications', models.TextField(default='')),
                ('timings', models.CharField(default='', max_length=100)),
                ('other_benefits', models.TextField(default='')),
                ('working_days_per_week', models.IntegerField(default=5)),
                ('interview_process', models.CharField(default='', max_length=255)),
                ('decision_maker', models.CharField(default='', max_length=100)),
                ('bond', models.TextField(default='', max_length=255)),
                ('rotational_shift', models.BooleanField()),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jobpostings')),
                ('username', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
