# Generated by Django 5.0.6 on 2025-01-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_jobapplication_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateexperiences',
            name='pay_slip1',
            field=models.FileField(blank=True, null=True, upload_to='Candidate/Experience/PaySlip1/'),
        ),
        migrations.AddField(
            model_name='candidateexperiences',
            name='pay_slip2',
            field=models.FileField(blank=True, null=True, upload_to='Candidate/Experience/PaySlip2/'),
        ),
        migrations.AddField(
            model_name='candidateexperiences',
            name='pay_slip3',
            field=models.FileField(blank=True, null=True, upload_to='Candidate/Experience/PaySlip3/'),
        ),
        migrations.AddField(
            model_name='candidateexperiences',
            name='relieving_letter',
            field=models.FileField(blank=True, null=True, upload_to='Candidate/Experience/Leter'),
        ),
    ]
