# Generated by Django 5.0.3 on 2024-06-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_jobpostingedited'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostingedited',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('rejected', 'rejected'), ('approved', 'approved')], default='pending', max_length=10),
        ),
    ]
