# Generated by Django 5.0.6 on 2025-06-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_interviewschedule_job_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostingdraftversion',
            name='description_file',
            field=models.FileField(blank=True, null=True, upload_to='Resumes/'),
        ),
        migrations.AddField(
            model_name='jobpostings',
            name='description_file',
            field=models.FileField(blank=True, null=True, upload_to='Resumes/'),
        ),
    ]
