# Generated by Django 5.0.6 on 2025-06-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_jobpostingdraftversion_description_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblocationsmodel',
            name='status',
            field=models.CharField(choices=[('opened', 'opened'), ('closed', 'closed')], default='opened', max_length=10),
        ),
    ]
