# Generated by Django 5.0.6 on 2025-01-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_recruiterprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateexperiences',
            name='reason_for_resignation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
