# Generated by Django 5.0.6 on 2025-01-31 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_candidateexperiences_reason_for_resignation'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostings',
            name='approval_status',
            field=models.CharField(default='accepted', max_length=10),
        ),
    ]
