# Generated by Django 5.0.6 on 2025-01-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_jobpostings_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostings',
            name='approval_status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
