# Generated by Django 5.0.6 on 2025-07-03 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_candidateprofile_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationterms',
            name='ctc_range',
            field=models.CharField(default='5,6', max_length=30),
        ),
        migrations.AlterField(
            model_name='organizationterms',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='app.organization'),
        ),
    ]
