# Generated by Django 5.0.6 on 2025-07-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_organizationterms_ctc_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiationrequests',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
