# Generated by Django 5.0.6 on 2025-02-06 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_customuser_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='current_salary',
            field=models.TextField(blank=True, default='50000'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='expected_salary',
            field=models.TextField(blank=True, default='70000'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='joining_details',
            field=models.TextField(blank=True, default='Can join in 7 days'),
        ),
        migrations.CreateModel(
            name='CandidateDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=50)),
                ('document', models.FileField(blank=True, null=True, upload_to='Candidate/Documents')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_documents', to='app.candidateprofile')),
            ],
        ),
    ]
