# Generated by Django 5.0.6 on 2025-07-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_negotiationrequests_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationterms',
            name='unique_code',
            field=models.CharField(default='ABC123', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='organizationterms',
            unique_together={('unique_code', 'organization')},
        ),
    ]
