# Generated by Django 5.0.3 on 2024-06-17 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_interviewsschedule_recruiter_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostingedited',
            name='is_assigned',
            field=models.ForeignKey(default='', limit_choices_to={'role': 'staff'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
