# Generated by Django 5.0.6 on 2025-07-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_organizationterms_unique_code_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organizationterms',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='organizationterms',
            name='unique_code',
            field=models.CharField(default='ABC123', max_length=30, unique=True),
        ),
    ]
