# Generated by Django 5.0.6 on 2025-02-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_candidateprofile_current_salary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateexperiences',
            name='status',
        ),
        migrations.AddField(
            model_name='candidateexperiences',
            name='is_working',
            field=models.BooleanField(default=False),
        ),
    ]
