# Generated by Django 5.0.6 on 2025-07-07 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_alter_organizationterms_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOrganizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_terms', models.CharField(blank=True, max_length=30, null=True)),
                ('approval_status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.clientdetails')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.organization')),
            ],
        ),
    ]
