# Generated by Django 5.0.6 on 2025-02-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_remove_candidateexperiences_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewschedule',
            name='meet_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interviewschedule',
            name='schedule_date',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
    ]
