# Generated by Django 5.0.3 on 2024-06-18 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_remove_jobpostingedited_is_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostingedited',
            name='job_department',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='jobpostings',
            name='job_department',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='candidateresume',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('rejected', 'rejected'), ('hold', 'hold'), ('pending', 'pending'), ('round1', 'round1'), ('round2', 'round2'), ('round3', 'round3'), ('shortlisted', 'shortlisted')], max_length=20, null=True),
        ),
    ]
