# Generated by Django 5.0.6 on 2025-02-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_interviewschedule_meet_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='round_status',
            field=models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('selected', 'selected'), ('rejected', 'rejected'), ('hold', 'hold'), ('pending', 'pending'), ('processing', 'processing')], default='applied', max_length=50),
        ),
    ]
