# Generated by Django 5.0.6 on 2025-07-07 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_clientorganizations'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clientorganizations',
            unique_together={('client', 'organization')},
        ),
    ]
