# Generated by Django 5.0.6 on 2025-02-10 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_jobapplication_round_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='round_status',
        ),
    ]
