# Generated by Django 5.0.6 on 2025-07-08 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_alter_clientorganizations_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientorganizations',
            name='accepted_terms',
        ),
        migrations.CreateModel(
            name='ClientOrganizationTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctc_range', models.CharField(default='5,6', max_length=30)),
                ('service_fee', models.DecimalField(decimal_places=2, default=8.33, max_digits=5)),
                ('description', models.TextField(default='')),
                ('replacement_clause', models.IntegerField(default=90)),
                ('invoice_after', models.IntegerField(default=30)),
                ('payment_within', models.IntegerField(default=7)),
                ('interest_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('client_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.clientorganizations')),
            ],
        ),
    ]
