# Generated by Django 5.0.6 on 2025-02-10 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_remove_jobapplication_round_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpostings',
            name='is_assigned',
        ),
        migrations.AlterField(
            model_name='jobpostingseditedversion',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.jobpostings'),
        ),
        migrations.AddField(
            model_name='jobpostings',
            name='is_assigned',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'recruiter'}, related_name='assigned_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
