# Generated by Django 5.0.6 on 2025-07-08 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_remove_clientorganizations_accepted_terms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negotiationrequests',
            name='client',
        ),
        migrations.RemoveField(
            model_name='negotiationrequests',
            name='organization',
        ),
        migrations.AddField(
            model_name='negotiationrequests',
            name='client_organization',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='app.clientorganizations'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='negotiationrequests',
            name='ctc_range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
