# Generated by Django 5.0.6 on 2025-07-08 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_remove_negotiationrequests_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientorganizationterms',
            name='is_negotiated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='negotiationrequests',
            name='client_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiation_requests', to='app.clientorganizations'),
        ),
        migrations.DeleteModel(
            name='ClientTermsAcceptance',
        ),
    ]
