# Generated by Django 5.0.6 on 2025-02-10 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_remove_jobpostings_is_assigned_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpostings',
            old_name='is_assigned',
            new_name='assigned_to',
        ),
    ]
