# Generated by Django 5.0.3 on 2024-06-18 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_alter_jobpostings_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpostings',
            name='interviewer_emails',
        ),
        migrations.RemoveField(
            model_name='jobpostings',
            name='interviewers',
        ),
    ]
