# Generated by Django 5.0.6 on 2025-07-08 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_clientorganizationterms_is_negotiated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpostingdraftversion',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='jobpostingdraftversion',
            name='is_linkedin_posted',
        ),
        migrations.RemoveField(
            model_name='jobpostingdraftversion',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='jobpostingdraftversion',
            name='status',
        ),
    ]
