# Generated by Django 5.0.6 on 2025-02-12 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_rename_is_assigned_jobpostings_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewschedule',
            name='from_time',
            field=models.TimeField(blank=True, default='00:00:00', null=True),
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='to_time',
            field=models.TimeField(blank=True, default='00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='interviewschedule',
            name='schedule_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
