# Generated by Django 5.0.3 on 2024-06-18 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_remove_jobpostings_interviewer_emails_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpostingedited',
            name='interview_process',
        ),
        migrations.RemoveField(
            model_name='jobpostings',
            name='interview_process',
        ),
    ]
