# Generated by Django 5.0.6 on 2025-07-08 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_remove_jobpostingdraftversion_approval_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostterms',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jobpostings'),
        ),
    ]
