# Generated by Django 5.0.6 on 2025-02-12 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_interviewschedule_from_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interviewschedule',
            old_name='schedule_date',
            new_name='scheduled_date',
        ),
    ]
