# Generated by Django 5.0.6 on 2025-02-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_rename_schedule_date_interviewschedule_scheduled_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
