# Generated by Django 5.0.3 on 2024-06-19 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_rounddetails_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rounddetails',
            old_name='candidate_name',
            new_name='candidate_id',
        ),
    ]
