# Generated by Django 5.0.6 on 2025-07-09 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_alter_jobpostterms_job_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobpostingdraftversion',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='jobpostingdraftversion',
            name='jobcode',
        ),
    ]
