# Generated by Django 5.0.6 on 2025-07-09 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_alter_jobpostingdraftversion_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobpostingdraftversion',
            unique_together={('username', 'organization')},
        ),
    ]
