# Generated by Django 5.0.6 on 2025-07-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_alter_jobpostingdraftversion_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostings',
            name='description_file',
            field=models.FileField(blank=True, null=True, upload_to='JobDescriptions/'),
        ),
    ]
