# Generated by Django 5.0.6 on 2025-07-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_alter_jobpostings_description_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostterms',
            name='is_negotiated',
            field=models.BooleanField(default=False),
        ),
    ]
