# Generated by Django 5.0.6 on 2025-07-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_jobpostterms_is_negotiated'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientorganizationterms',
            name='service_fee_type',
            field=models.CharField(choices=[('percentage', 'percentage'), ('fixed', 'fixed')], default='percentage', max_length=20),
        ),
    ]
