# Generated by Django 5.0.3 on 2024-06-20 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_resumebank'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewsScheduleEdited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_description', models.TextField()),
                ('interview_time', models.DateTimeField(default='')),
                ('round_num', models.IntegerField()),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.interviewerdetails')),
                ('recruiter_id', models.ForeignKey(limit_choices_to={'role': 'recruiter'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('resume_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.candidateresume')),
            ],
        ),
    ]
