# Generated by Django 5.0.6 on 2024-06-20 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_interviewsscheduleedited'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewsDetailsEdited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_num', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('type_of_interview', models.CharField(choices=[('face_to_face', 'face_to_face'), ('online', 'online'), ('telephone', 'telephone')], max_length=20)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.interviewerdetails')),
            ],
        ),
        migrations.DeleteModel(
            name='InterviewsScheduleEdited',
        ),
    ]
