# Generated by Django 5.0.6 on 2025-07-10 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_clientorganizationterms_service_fee_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientorganizationterms',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=8.33, max_digits=15),
        ),
    ]
