# Generated by Django 5.0.6 on 2024-06-20 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_interviewsdetailsedited_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InterviewsDetailsEdited',
            new_name='InterviewerDetailsEdited',
        ),
    ]
