# Generated by Django 5.0.6 on 2025-07-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_alter_clientorganizationterms_service_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiationrequests',
            name='service_fee_type',
            field=models.CharField(choices=[('percentage', 'percentage'), ('fixed', 'fixed')], default='percentage', max_length=20),
        ),
    ]
