# Generated by Django 5.0.6 on 2025-07-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_negotiationrequests_service_fee_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblocationsmodel',
            name='positions_closed',
            field=models.IntegerField(default=0),
        ),
    ]
