# Generated by Django 5.0.6 on 2024-06-20 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_rename_interviewsdetailsedited_interviewerdetailsedited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewerdetailsedited',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jobpostings'),
        ),
    ]
