# Generated by Django 5.0.6 on 2024-06-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_alter_interviewerdetailsedited_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewerdetailsedited',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
