# Generated by Django 5.0.6 on 2025-07-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_joblocationsmodel_positions_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
