# Generated by Django 5.0.6 on 2025-07-10 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_jobapplication_is_closed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'default_manager_name': 'objects'},
        ),
    ]
