# Generated by Django 5.0.6 on 2024-06-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_interviewerdetailsedited_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewerdetailsedited',
            name='edited_by',
            field=models.CharField(default='', max_length=20),
        ),
    ]
