# Generated by Django 5.0.6 on 2025-07-11 06:33

import django.db.models.deletion
from django.db import migrations, models
from django.utils.timezone import now


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_alter_jobapplication_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicegenerated',
            old_name='status',
            new_name='payment_status',
        ),
        migrations.RemoveField(
            model_name='invoicegenerated',
            name='client_email',
        ),
        migrations.RemoveField(
            model_name='invoicegenerated',
            name='organization_email',
        ),
        migrations.AddField(
            model_name='invoicegenerated',
            name='cgst',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='invoicegenerated',
            name='final_price',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='invoicegenerated',
            name='invoice_calculated',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='invoicegenerated',
            name='invoice_status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Sent', 'Sent')], default='Scheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='invoicegenerated',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoicegenerated',
            name='scheduled_date',
            field=models.DateTimeField(default=now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoicegenerated',
            name='sgst',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='invoicegenerated',
            name='application',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='app.jobapplication'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoicegenerated',
            name='client',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='app.clientdetails'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoicegenerated',
            name='organization',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='app.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoicegenerated',
            name='payment_method',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='invoicegenerated',
            name='payment_transaction_id',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='invoicegenerated',
            name='terms_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.organizationterms'),
        ),
        migrations.CreateModel(
            name='InvoiceNotificationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255)),
                ('scheduled_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.invoicegenerated')),
            ],
        ),
    ]
