# Generated by Django 5.0.6 on 2024-06-25 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_interviewerdetailsedited_edited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumebank',
            name='freeze_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
