# Generated by Django 5.0.6 on 2025-07-11 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_rename_status_invoicegenerated_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicegenerated',
            name='application',
        ),
        migrations.AddField(
            model_name='invoicegenerated',
            name='selected_candidate',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='app.selectedcandidates'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoicegenerated',
            name='terms_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jobpostterms'),
        ),
    ]
