# Generated by Django 5.0.6 on 2024-06-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_resumebank_freeze_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostings',
            name='update_status',
            field=models.BooleanField(default=True),
        ),
    ]
