# Generated by Django 5.0.6 on 2025-07-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_remove_invoicegenerated_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostterms',
            name='service_fee_type',
            field=models.CharField(choices=[('percentage', 'percentage'), ('fixed', 'fixed')], default='percentage', max_length=30),
        ),
    ]
