# Generated by Django 5.0.6 on 2024-06-25 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_jobpostings_update_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpostings',
            name='update_status',
        ),
    ]
