# Generated by Django 5.0.6 on 2025-07-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_jobpostterms_service_fee_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostterms',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=8.33, max_digits=20),
        ),
    ]
