# Generated by Django 5.0.6 on 2024-06-25 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_remove_jobpostings_update_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostingedited',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.jobpostings'),
        ),
        migrations.AlterField(
            model_name='jobpostingedited',
            name='job_title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
