# Generated by Django 5.0.6 on 2024-06-25 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_alter_jobpostingedited_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostingedited',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.jobpostings'),
        ),
    ]
