# Generated by Django 5.0.6 on 2025-07-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_alter_jobpostterms_service_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostterms',
            name='ctc_range',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
