# Generated by Django 5.0.6 on 2024-06-26 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_alter_jobpostingedited_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('name_of_organization', models.CharField(max_length=200)),
                ('designation', models.TextField()),
                ('contact_number', models.IntegerField()),
                ('website_url', models.URLField()),
                ('gst', models.CharField(max_length=100)),
                ('company_pan', models.CharField(max_length=20)),
                ('company_address', models.TextField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
