# Generated by Django 5.0.6 on 2025-07-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_jobpostterms_ctc_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetails',
            name='company_pan',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website_url',
            field=models.CharField(max_length=255),
        ),
    ]
