# Generated by Django 5.0.6 on 2024-06-27 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_clientdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumebank',
            name='address',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='resumebank',
            name='age',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='resumebank',
            name='cover_letter',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='resumebank',
            name='first_name',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='resumebank',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('transgender', 'transgender')], default='male', max_length=15),
        ),
        migrations.AddField(
            model_name='resumebank',
            name='last_name',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='resumebank',
            name='middle_name',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='resumebank',
            name='position',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
