# Generated by Django 5.0.6 on 2025-07-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_feature_plan_organizationplan_planfeature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='company_pan',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
