# Generated by Django 5.0.6 on 2024-06-27 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_resumebank_address_resumebank_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateresume',
            name='job_dept',
        ),
    ]
