# Generated by Django 5.0.6 on 2025-07-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_alter_organization_company_pan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='company_address',
            field=models.CharField(max_length=255),
        ),
    ]
