# Generated by Django 5.0.6 on 2024-06-27 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_remove_candidateresume_job_dept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumebank',
            name='alternate_contact_number',
        ),
        migrations.RemoveField(
            model_name='resumebank',
            name='candidate_email',
        ),
        migrations.RemoveField(
            model_name='resumebank',
            name='candidate_name',
        ),
        migrations.RemoveField(
            model_name='resumebank',
            name='contact_number',
        ),
        migrations.AlterField(
            model_name='resumebank',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('transgender', 'transgender')], max_length=15),
        ),
    ]
