# Generated by Django 5.0.6 on 2025-07-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_alter_organization_company_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicegenerated',
            name='invoice_code',
            field=models.CharField(default='123', max_length=50, unique=True),
        ),
    ]
