# Generated by Django 5.0.6 on 2025-07-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_invoicegenerated_invoice_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicegenerated',
            name='igst',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=30, null=True),
        ),
    ]
