# Generated by Django 5.0.6 on 2025-07-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_invoicegenerated_sub_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetails',
            name='gst_number',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='clientdetails',
            name='website_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='organization',
            name='gst_number',
            field=models.CharField(blank=True, default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
