# Generated by Django 5.0.6 on 2025-07-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_alter_clientdetails_gst_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negotiationrequests',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=8.33, max_digits=10),
        ),
    ]
