# Generated by Django 5.0.6 on 2025-07-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_alter_negotiationrequests_service_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostings',
            name='extended_deadline',
            field=models.DateField(null=True),
        ),
    ]
