# Generated by Django 5.0.6 on 2025-07-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_jobpostings_extended_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewschedule',
            name='status',
            field=models.CharField(choices=[('scheduled', 'scheduled'), ('pending', 'pending'), ('completed', 'completed'), ('cancelled', 'cancelled'), ('reschedule', 'reschedule'), ('not_joined', 'not_joined')], default='scheduled', max_length=20),
        ),
    ]
