# Generated by Django 5.0.6 on 2025-07-31 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_alter_interviewschedule_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateresume',
            name='highest_qualification',
            field=models.CharField(blank=True, default='B Tech', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_application', to='app.candidateresume'),
        ),
    ]
