# Generated by Django 5.0.6 on 2025-08-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_alter_candidateresume_highest_qualification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='about',
            field=models.TextField(blank=True, default=''),
        ),
    ]
