# Generated by Django 5.0.6 on 2025-08-13 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0075_blogimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPostLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='app.jobpostings')),
            ],
        ),
    ]
