# Generated by Django 5.0.6 on 2025-08-14 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0075_blogimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='account_number',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='bank_holder_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='ifsc_code',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='msme_number',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='udaan_number',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
