# Generated by Django 5.0.6 on 2025-08-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0076_organization_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientorganizations',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='category',
            field=models.CharField(blank=True, choices=[('negotiated_terms', 'NegotiatedTerms'), ('reject_terms', 'RejectTerms'), ('accept_terms', 'AcceptTerms'), ('create_job', 'CreateJob'), ('assign_interviewer', 'AssignInterviewer'), ('accept_job', 'AcceptJob'), ('edit_job', 'EditJob'), ('accept_job_edit', 'AcceptJobEdit'), ('reject_job_edit', 'RejectJobEdit'), ('partial_job_edit', 'PartialJobEdit'), ('reject_job', 'RejectJob'), ('assign_job', 'AssignJob'), ('send_application', 'SendApplication'), ('shortlist_application', 'ShortlistApplication'), ('schedule_interview', 'ScheduleInterview'), ('promote_candidate', 'PromoteCandidate'), ('reject_candidate', 'RejectCandidate'), ('onhold_candidate', 'OnHoldCandidate'), ('select_candidate', 'SelectCandidate'), ('accepted_ctc', 'AcceptedCTC'), ('candidate_accepted', 'CandidateAccepted'), ('candidate_rejected', 'CandidateRejected'), ('candidate_left', 'CandidateLeft'), ('candidate_joined', 'CandidateJoined'), ('sent_connection', 'SentConnection')], max_length=60, null=True),
        ),
    ]
