# Generated by Django 5.0.6 on 2025-08-18 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0077_clientorganizations_is_seen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostings',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='InterviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='app.interviewschedule')),
            ],
        ),
        migrations.CreateModel(
            name='JobPostLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='app.jobpostings')),
            ],
        ),
        migrations.CreateModel(
            name='JobProfileLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='app.jobapplication')),
            ],
        ),
    ]
