# Generated by Django 5.0.6 on 2026-01-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0078_jobpostings_is_seen_interviewlog_jobpostlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostings',
            name='is_edited_by_client',
            field=models.BooleanField(default=False),
        ),
    ]
