# Generated by Django 5.0.6 on 2026-01-27 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0079_jobpostings_is_edited_by_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobEditRequestsByClient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('edit_status', models.CharField(default='pending', max_length=10)),
                ('edit_reason', models.TextField()),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('job_department', models.CharField(blank=True, max_length=100, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('years_of_experience', models.TextField(blank=True, max_length=100, null=True)),
                ('ctc', models.CharField(blank=True, max_length=50, null=True)),
                ('rounds_of_interview', models.IntegerField(blank=True, null=True)),
                ('job_type', models.CharField(blank=True, max_length=100, null=True)),
                ('probation_type', models.CharField(blank=True, max_length=20)),
                ('probation_period', models.CharField(blank=True, max_length=30)),
                ('job_level', models.CharField(blank=True, max_length=100)),
                ('qualifications', models.TextField(blank=True, null=True)),
                ('timings', models.CharField(blank=True, max_length=100, null=True)),
                ('other_benefits', models.TextField(blank=True, null=True)),
                ('working_days_per_week', models.IntegerField(blank=True, null=True)),
                ('decision_maker', models.CharField(blank=True, max_length=100)),
                ('decision_maker_email', models.CharField(blank=True, max_length=100)),
                ('bond', models.TextField(blank=True, max_length=255)),
                ('rotational_shift', models.BooleanField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='opened', max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('age', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=30, null=True)),
                ('visa_status', models.CharField(blank=True, max_length=100, null=True)),
                ('passport_availability', models.CharField(blank=True, max_length=50, null=True)),
                ('time_period', models.CharField(blank=True, default=' ', max_length=50)),
                ('notice_period', models.CharField(blank=True, max_length=30, null=True)),
                ('notice_time', models.CharField(blank=True, default=' ', max_length=30)),
                ('industry', models.CharField(blank=True, max_length=40, null=True)),
                ('differently_abled', models.CharField(blank=True, max_length=40, null=True)),
                ('languages', models.CharField(blank=True, max_length=100, null=True)),
                ('job_close_duration', models.DateField(blank=True, null=True)),
                ('extended_deadline', models.DateField(blank=True, null=True)),
                ('approval_status', models.CharField(blank=True, default='pending', max_length=10, null=True)),
                ('reason', models.TextField(blank=True, default='', null=True)),
                ('is_linkedin_posted', models.BooleanField(default=False)),
                ('is_seen', models.BooleanField(default=False)),
                ('edited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jobpostings')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.organization')),
            ],
        ),
    ]
