# Generated by Django 5.0.6 on 2026-01-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0080_jobeditrequestsbyclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobeditrequestsbyclient',
            name='job_locations',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
