# Generated by Django 5.0.6 on 2026-02-03 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0081_jobeditrequestsbyclient_job_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostings',
            name='industry',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='category',
            field=models.CharField(blank=True, choices=[('negotiated_terms', 'NegotiatedTerms'), ('reject_terms', 'RejectTerms'), ('accept_terms', 'AcceptTerms'), ('create_job', 'CreateJob'), ('assign_interviewer', 'AssignInterviewer'), ('accept_job', 'AcceptJob'), ('edit_job', 'EditJob'), ('accept_job_edit', 'AcceptJobEdit'), ('reject_job_edit', 'RejectJobEdit'), ('partial_job_edit', 'PartialJobEdit'), ('reject_job', 'RejectJob'), ('assign_job', 'AssignJob'), ('send_application', 'SendApplication'), ('shortlist_application', 'ShortlistApplication'), ('schedule_interview', 'ScheduleInterview'), ('promote_candidate', 'PromoteCandidate'), ('reject_candidate', 'RejectCandidate'), ('onhold_candidate', 'OnHoldCandidate'), ('select_candidate', 'SelectCandidate'), ('accepted_ctc', 'AcceptedCTC'), ('candidate_accepted', 'CandidateAccepted'), ('candidate_rejected', 'CandidateRejected'), ('candidate_left', 'CandidateLeft'), ('candidate_joined', 'CandidateJoined'), ('sent_connection', 'SentConnection'), ('accept_connection', 'AcceptConnection')], max_length=60, null=True),
        ),
        migrations.CreateModel(
            name='TOPUP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sms_limit', models.IntegerField(default=0)),
                ('whatsapp_limit', models.IntegerField(default=0)),
                ('email_limit', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.organization')),
            ],
        ),
        migrations.CreateModel(
            name='SMSUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.organization')),
                ('topup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_usages', to='app.topup')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.organization')),
                ('topup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_usages', to='app.topup')),
            ],
        ),
    ]
