# Generated by Django 5.0.6 on 2026-02-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0085_alter_notifications_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='category',
            field=models.CharField(blank=True, choices=[('negotiated_terms', 'NegotiatedTerms'), ('reject_terms', 'RejectTerms'), ('accept_terms', 'AcceptTerms'), ('create_job', 'CreateJob'), ('assign_interviewer', 'AssignInterviewer'), ('accept_job', 'AcceptJob'), ('edit_job', 'EditJob'), ('accept_job_edit', 'AcceptJobEdit'), ('reject_job_edit', 'RejectJobEdit'), ('partial_job_edit', 'PartialJobEdit'), ('reject_job', 'RejectJob'), ('assign_job', 'AssignJob'), ('send_application', 'SendApplication'), ('shortlist_application', 'ShortlistApplication'), ('schedule_interview', 'ScheduleInterview'), ('promote_candidate', 'PromoteCandidate'), ('reject_candidate', 'RejectCandidate'), ('onhold_candidate', 'OnHoldCandidate'), ('select_candidate', 'SelectCandidate'), ('accepted_ctc', 'AcceptedCTC'), ('candidate_accepted', 'CandidateAccepted'), ('candidate_rejected', 'CandidateRejected'), ('candidate_left', 'CandidateLeft'), ('candidate_joined', 'CandidateJoined'), ('sent_connection', 'SentConnection'), ('accept_connection', 'AcceptConnection'), ('candidate_edit_request', 'CandidateEditRequest'), ('candidate_joining_date_update', 'CandidateJoiningDateUpdate'), ('invoice_generated', 'InvoiceGenerated'), ('plan_limit_reject', 'PlanLimitReject'), ('manager_viewed_job', 'ManagerViewedJob'), ('ticket_raised', 'TicketRaised'), ('ticket_reply', 'TicketReply'), ('ticket_status_update', 'TicketStatusUpdate'), ('blog_submitted', 'BlogSubmitted'), ('blog_approved', 'BlogApproved'), ('blog_rejected', 'BlogRejected'), ('job_near_deadline', 'JobNearDeadline'), ('job_expired', 'JobExpired'), ('feedback_pending', 'FeedbackPending')], max_length=60, null=True),
        ),
    ]
