# Generated by Django 5.0.6 on 2026-02-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0086_alter_notifications_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='category',
            field=models.CharField(blank=True, choices=[('negotiated_terms', 'NegotiatedTerms'), ('reject_terms', 'RejectTerms'), ('accept_terms', 'AcceptTerms'), ('create_job', 'CreateJob'), ('assign_interviewer', 'AssignInterviewer'), ('accept_job', 'AcceptJob'), ('edit_job', 'EditJob'), ('accept_job_edit', 'AcceptJobEdit'), ('reject_job_edit', 'RejectJobEdit'), ('partial_job_edit', 'PartialJobEdit'), ('reject_job', 'RejectJob'), ('assign_job', 'AssignJob'), ('send_application', 'SendApplication'), ('shortlist_application', 'ShortlistApplication'), ('schedule_interview', 'ScheduleInterview'), ('promote_candidate', 'PromoteCandidate'), ('reject_candidate', 'RejectCandidate'), ('onhold_candidate', 'OnHoldCandidate'), ('select_candidate', 'SelectCandidate'), ('accepted_ctc', 'AcceptedCTC'), ('candidate_accepted', 'CandidateAccepted'), ('candidate_rejected', 'CandidateRejected'), ('candidate_left', 'CandidateLeft'), ('candidate_joined', 'CandidateJoined'), ('sent_connection', 'SentConnection'), ('accept_connection', 'AcceptConnection'), ('candidate_edit_request', 'CandidateEditRequest'), ('candidate_joining_date_update', 'CandidateJoiningDateUpdate'), ('invoice_generated', 'InvoiceGenerated'), ('plan_limit_reject', 'PlanLimitReject'), ('manager_viewed_job', 'ManagerViewedJob'), ('ticket_raised', 'TicketRaised'), ('ticket_reply', 'TicketReply'), ('ticket_status_update', 'TicketStatusUpdate'), ('blog_submitted', 'BlogSubmitted'), ('blog_approved', 'BlogApproved'), ('blog_rejected', 'BlogRejected'), ('job_near_deadline', 'JobNearDeadline'), ('job_expired', 'JobExpired'), ('feedback_pending', 'FeedbackPending'), ('interview_feedback_added', 'InterviewFeedbackAdded'), ('recruiter_assigned_to_job', 'RecruiterAssignedToJob'), ('candidate_offer_rejected', 'CandidateOfferRejected'), ('replacement_request', 'ReplacementRequest'), ('replacement_accepted', 'ReplacementAccepted'), ('replacement_rejected', 'ReplacementRejected')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='replacementcandidates',
            name='status',
            field=models.CharField(choices=[('no', 'no'), ('pending_manager_approval', 'pending_manager_approval'), ('pending', 'pending'), ('completed', 'completed'), ('incomplete', 'incomplete')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='selectedcandidates',
            name='replacement_status',
            field=models.CharField(choices=[('no', 'no'), ('pending_manager_approval', 'pending_manager_approval'), ('pending', 'pending'), ('completed', 'completed'), ('incomplete', 'incomplete')], default='no', max_length=50),
        ),
    ]
