# Generated by Django 5.0.6 on 2026-02-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0087_alter_notifications_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('selected', 'selected'), ('rejected', 'rejected'), ('hold', 'hold'), ('pending', 'pending'), ('processing', 'processing'), ('job_closed', 'job_closed'), ('left', 'left')], default='applied', max_length=50),
        ),
    ]
