# Generated by Django 5.0.6 on 2026-02-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0088_alter_jobapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='target_in_positions',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='target_in_rupees',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
