# Generated by Django 5.0.6 on 2026-02-18 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0089_recruiterprofile_target_in_positions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile_skills', to='app.candidateprofile')),
            ],
        ),
    ]
