# Generated by Django 5.0.6 on 2026-02-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0090_candidateskills'),
    ]

    operations = [
        migrations.AddField(
            model_name='replacementcandidates',
            name='suggested_candidates',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
