# Generated by Django 5.0.6 on 2026-02-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0092_alter_notifications_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_replacement',
            field=models.BooleanField(default=False),
        ),
    ]
