# Generated by Django 5.0.6 on 2026-02-24 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0093_jobapplication_is_replacement'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiationrequests',
            name='original_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='negotiation_requests_linked', to='app.clientorganizationterms'),
        ),
    ]
