# Generated by Django 5.0.6 on 2026-02-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0094_negotiationrequests_original_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='visited',
            field=models.BooleanField(default=False),
        ),
    ]
