# Generated by Django 5.0.6 on 2026-03-02 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0095_notifications_visited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblocationsmodel',
            name='status',
            field=models.CharField(choices=[('opened', 'opened'), ('closed', 'closed'), ('expired', 'expired')], default='opened', max_length=10),
        ),
        migrations.CreateModel(
            name='ManagerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_in_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('target_in_positions', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
