# Generated by Django 5.0.6 on 2025-05-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_customuser_first_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='first_login',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
    ]
